name: Build

on:
  push:
    branches: [ main ]

jobs:
  buildAndTest:
    runs-on: windows-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup Chrome and Chrome Driver
      uses: nanasess/setup-chromedriver@master
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v1
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path .\.sonar\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: powershell
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"mingyaulee_WebExtension.Net" /o:"mingyaulee" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths="src/Tests/TestResults/*.trx" /d:sonar.cs.opencover.reportsPaths="src/Tests/TestResults/**/*.opencover.xml" /d:sonar.coverage.exclusions="src/Tests/**/*.*,src/WebExtension.Net.Generator/**/*.*"
        dotnet build ./src --configuration Release
        dotnet test ./src --no-restore --no-build --configuration Release --logger "console;verbosity=detailed" --collect "XPlat Code Coverage" --results-directory ./src/Tests/TestResults -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

  tag:
    needs: buildAndTest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: 5.x
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
    - name: Check if tag exists
      id: tagExistsCheck
      shell: bash
      run: git show-ref --tags --verify --quiet -- "refs/tags/v${{ steps.gitversion.outputs.SemVer }}" && echo "::set-output name=tagExists::1" || echo "::set-output name=tagExists::0"
    - name: Create tag
      if: steps.tagExistsCheck.outputs.tagExists == 0
      uses: negz/create-tag@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: v${{ steps.gitversion.outputs.SemVer }}
